### ISSUE TITLE
Why was cuGetProcAddress manually deleted?

### ISSUE THREAD

**Issue by chaunceyjiang** [Bruce-Lee-LY/cuda_hook#12]
Recently, I have been studying this project and noticed that you manually removed the interception of `cuGetProcAddress`. May I ask why?

https://github.com/Bruce-Lee-LY/cuda_hook/blob/fc4b02e14889bdbcc973fddc8d03daaa99e0433b/src/cuda/cuda_hook.cpp#L3313-L3321

**Comment by Bruce-Lee-LY** [comment]
Just a trick.
