### ISSUE TITLE
BUG:  `dlopen("/usr/local/cuda/targets/x86_64-linux/lib/libcublas.so", RTLD_NOW | RTLD_LOCAL)` failed, symbol free_gemm_select version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

### ISSUE THREAD

**Issue by githubcq** [Bruce-Lee-LY/cuda_hook#13]
When execute tensorflow minist train task, occur the problem, 'Check failed: cublas_handle'.

It caused by dlopen, the complete command is `dlopen("/usr/local/cuda/targets/x86_64-linux/lib/libcublas.so", RTLD_NOW | RTLD_LOCAL)`. And error throwed by dlopen is 'Failed to open /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so: /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so: symbol free_gemm_select version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference'.

According to ldd and nm, libcublas.so depend on libcublasLt.so.11, which linked to '/home/chenqian/Code/cuda_hook/output/lib64/libcublasLt.so.11'. And, there is no symbol `free_gemm_select` in both '/home/chenqian/Code/cuda_hook/output/lib64/libcublasLt.so.11' and '/usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so.11'.

Moreover, if without cuda hook, the train task can complete.

<img width="678" alt="Screenshot 2024-04-23 at 2 28 40 PM" src="https://github.com/Bruce-Lee-LY/cuda_hook/assets/67734391/283036dc-7a0a-490c-9ce0-28061244d6c2">

<img width="1511" alt="Screenshot 2024-04-23 at 1 58 17 PM" src="https://github.com/Bruce-Lee-LY/cuda_hook/assets/67734391/fc80588b-2010-4204-a3a2-09ebdd538b58">

<img width="1510" alt="Screenshot 2024-04-23 at 1 58 54 PM" src="https://github.com/Bruce-Lee-LY/cuda_hook/assets/67734391/936e042c-2325-47e9-bc3b-6737206977a6">

<img width="1155" alt="Screenshot 2024-04-23 at 2 02 45 PM" src="https://github.com/Bruce-Lee-LY/cuda_hook/assets/67734391/3b8e75bd-6e1c-409e-9beb-25542e24680b">

**Comment by Bruce-Lee-LY** [comment]
You need to hijack free_gemm_select.
