### ISSUE TITLE
It doesn't work with the newer driver and CUDA

### ISSUE THREAD

**Issue by wangh0606** [Bruce-Lee-LY/cuda_hook#2]
It seems that it works with CUDA 11.6 and fails to work with CUDA 11.8  with Driver Version 525.85.12. Could you please fix it?

The following is the error message.
$ more log/sample/nvml/nvml_example.log
[CUDA-HOOK 71169:71169 hook.h:33 GetNVMLSymbol] check failed: nvml_handle

$ more matrix_mul.log
/home/ps/cuda_hook_retry/output/sample/cuda/matrix_mul: /home/ps/cuda_hook_retry/output/lib64/libcudart.so.11.0: no version information available (required by /home/ps/cuda
_hook_retry/output/sample/cuda/matrix_mul)
[CUDA-HOOK 71167:71167 hook.h:29 GetCUDASymbol] check failed: cuda_handle
[Matrix Multiply Using CUDA] - Starting...

**Comment by Bruce-Lee-LY** [comment]
CUDA 11.8, based on Driver Version 520.61.05, was actually tested and the cuda_hook worked. So you'd better check your hook environment configuration.

**Comment by wangh0606** [comment]
Thanks for your quick reply! I am compiling the code on Centos 7 with GCC 7.3, the driver is 520.61.05, cuda is 11.8.
It shows the following error when I run run_sample.sh.
 [CUDA-HOOK 24060:24060 hook.h:33 GetNVMLSymbol] check failed: nvml_handle
Could you tell me how to fix it?

**Comment by Bruce-Lee-LY** [comment]
The cuda driver dynamic library path of centos and ubuntu is different. You may need to change the path of s_nvml_dso（/usr/lib or the path specified when cuda driver is installed）.
