### ISSUE TITLE
Where or How to get the cuda_subset.h?

### ISSUE THREAD

**Issue by pokerfaceSad** [Bruce-Lee-LY/cuda_hook#3]
Hi @Bruce-Lee-LY , Where or How to get the cuda_subset.h?

**Comment by Bruce-Lee-LY** [comment]
All subset comes from header files in the cuda toolkit, such as definitions of structs and enumerations etc.

**Comment by Bruce-Lee-LY** [comment]
There is currently no script to do this.
There are many hidden symbols in cuda, these symbols are not defined in the cuda toolkit, such as nvmlInternalGetExportTable, could be found only by some means of disassembly.

**Comment by pokerfaceSad** [comment]
I'm a little confused about why there has no definition about `nvmlInternalGetExportTable ` in `nvml_hook.cpp`, but it was indeed hooked according to the log?

**Comment by Bruce-Lee-LY** [comment]
I tested it on the nvmi sample and it didn't repeat your problem. In theory, this could not be the case.
- CUDA: 11.8
- CUDA Driver: 525.125.06
- GPU: RTX3080Ti Laptop
- Ubuntu22.04

**Comment by pokerfaceSad** [comment]
You can try to reproduce by hook `nvidia-smi` like `LD_LIBRARY_PATH=/path/to/libcuda_hook.so nvidia-smi`.

**Comment by Bruce-Lee-LY** [comment]
I can't reproduce your problem using the method you provided.
