### ISSUE TITLE
ports to cuda 12. 

### ISSUE THREAD

**Issue by idreamerhx** [Bruce-Lee-LY/cuda_hook#7]
Hi, 

after code_generation for 12.3
build.sh

I got matex_mul:

CUDA error at /opt/cuda_hook/sample/cuda/include/helper_cuda.h:739 code=36(cudaErrorCallRequiresNewerDriver) "cudaGetDeviceCount(&device_count)"

[root@xxxxbuild]# strings ./* | grep -i versi |grep 12
strings: Warning: './CMakeFiles' is a directory
CUDA_VERSION:STRING=12.3

Is this problem relate to cuda_subset.h  ?

**Comment by Bruce-Lee-LY** [comment]
It has not been tested on cuda12.3 yet. The error message shows that the cuda driver API has been updated.
